-- PostgreSQL schema for fingerprint_attendance
-- Converted from the MySQL dump dated 2026-04-26.

BEGIN;

DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS scan_sessions CASCADE;
DROP TABLE IF EXISTS enroll_commands CASCADE;
DROP TABLE IF EXISTS subject_teachers CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS attendance_status CASCADE;
DROP TYPE IF EXISTS enroll_command_status CASCADE;
DROP TYPE IF EXISTS scan_session_status CASCADE;
DROP TYPE IF EXISTS session_status CASCADE;
DROP TYPE IF EXISTS subject_teacher_role CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;

CREATE TYPE attendance_status AS ENUM ('Present', 'Absent', 'Late');
CREATE TYPE enroll_command_status AS ENUM ('pending', 'done');
CREATE TYPE scan_session_status AS ENUM ('idle', 'scanning', 'closed');
CREATE TYPE session_status AS ENUM ('scheduled', 'live', 'finished');
CREATE TYPE subject_teacher_role AS ENUM ('primary', 'co-teacher');
CREATE TYPE user_role AS ENUM ('student', 'teacher', 'admin');

CREATE TABLE users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL UNIQUE,
    email varchar(120),
    password_hash varchar(255) NOT NULL,
    role user_role NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE devices (
    device_id varchar(50) PRIMARY KEY,
    room_name varchar(100) NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE teachers (
    teacher_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer UNIQUE REFERENCES users(user_id) ON DELETE SET NULL,
    full_name varchar(200) NOT NULL,
    phone varchar(30)
);

CREATE TABLE students (
    student_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer UNIQUE REFERENCES users(user_id) ON DELETE SET NULL,
    student_code varchar(50) UNIQUE,
    full_name varchar(200) NOT NULL,
    year_level integer,
    fingerprint_id integer,
    template_data text
);

CREATE TABLE subjects (
    subject_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_name varchar(150) NOT NULL,
    teacher_id integer NOT NULL REFERENCES teachers(teacher_id) ON DELETE CASCADE,
    academic_year varchar(10)
);

CREATE TABLE subject_teachers (
    subject_id integer NOT NULL REFERENCES subjects(subject_id) ON DELETE CASCADE,
    teacher_id integer NOT NULL REFERENCES teachers(teacher_id) ON DELETE CASCADE,
    role subject_teacher_role DEFAULT 'co-teacher',
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (subject_id, teacher_id)
);

CREATE TABLE enrollments (
    enrollment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
    subject_id integer NOT NULL REFERENCES subjects(subject_id) ON DELETE CASCADE,
    enrolled_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_enrollment UNIQUE (student_id, subject_id)
);

CREATE TABLE sessions (
    session_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id integer NOT NULL REFERENCES subjects(subject_id) ON DELETE CASCADE,
    date date NOT NULL,
    start_time time NOT NULL,
    end_time time,
    status session_status DEFAULT 'scheduled',
    created_by integer,
    late_condition integer DEFAULT 15,
    absent_condition integer DEFAULT 30
);

CREATE TABLE scan_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id integer,
    session_id integer,
    status scan_session_status DEFAULT 'idle',
    started_at timestamptz,
    device_id varchar(50) DEFAULT 'ROOM_1_SCANNER'
);

CREATE TABLE enroll_commands (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer,
    fingerprint_id integer,
    status enroll_command_status DEFAULT 'pending',
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    device_id varchar(50) DEFAULT 'ROOM_1_SCANNER'
);

CREATE TABLE attendance (
    attendance_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer REFERENCES students(student_id) ON DELETE SET NULL,
    session_id integer REFERENCES sessions(session_id) ON DELETE CASCADE,
    time_stamp timestamptz DEFAULT CURRENT_TIMESTAMP,
    status attendance_status DEFAULT 'Present',
    fingerprint_id integer,
    device_id varchar(50)
);

CREATE INDEX idx_att_session ON attendance(session_id);
CREATE INDEX idx_att_student ON attendance(student_id);
CREATE INDEX idx_enrollments_subject ON enrollments(subject_id);
CREATE INDEX idx_sessions_subject ON sessions(subject_id);
CREATE INDEX idx_subjects_teacher ON subjects(teacher_id);
CREATE INDEX idx_subject_teachers_teacher ON subject_teachers(teacher_id);

INSERT INTO devices (device_id, room_name)
VALUES ('ROOM_1_SCANNER', 'Room 1 (Default Scanner)')
ON CONFLICT (device_id) DO NOTHING;

COMMIT;
